### ISSUE TITLE
Records are repeatedly presented to Cloudlog

### ISSUE THREAD

**Issue by timkirby** [M0LTE/adifpush#1]
It would appear that records are repeatedly uploaded to Cloudlog.

eg

Uploaded QSO with 9A5CW

Then next time a contact is logged

Uploaded QSO with 9A5CW
Uploaded QSO with 9A5CW
Uploaded QSO with HA9JDI

Then the next time a contact is logged 

Uploaded QSO with 9A5CW
Uploaded QSO with HA9JDI
Uploaded QSO with 9A6R

And so on.

Doesn't really matter as Cloudlog filters out the dupes, but I guess it would be good to keep the uploads small, if possible!

Thanks for your work!

**Comment by M0LTE** [comment]
Hi Tim, just found this! 2.5 years later - adifpush now listens to WSJT-X's UDP interface rather than watching the filesystem. 

Hope you're well!
Tom

**Comment by timkirby** [comment]
Hi Tom,

Thanks! I’m pretty sure you fixed this at the time because I haven’t seen this happen for a long while.

Great about now listening on UDP, that’s an excellent idea. I’m still using the file based version here - it runs without complaining - thank you so much!

Yes, all good here and hope you are too.

Very best wishes,

Tim
