### ISSUE TITLE
ADIF records out of sequence do not get uploaded to Cloudlog

### ISSUE THREAD

**Issue by timkirby** [M0LTE/adifpush#2]
I just stumbled across a funny - which you may be able to do something about - you may not - either is cool!

I called MW1BAJ only for him to fade out.
G4BNM popped up, so I worked him. In the middle of the G4BNM QSO, MW1BAJ appears, sending me a report. I complete the G4BNM QSO and log him, which is uploaded to Cloudlog.

I then reply to MW1BAJ sending a R report and then complete with him. I hit 'Log QSO' and the QSO is not uploaded to Cloudlog.

I think this is because the START time of the MW1BAJ QSO is before the G4BNM Start time, so the program thinks it's already been uploaded.

Make sense?

**Comment by M0LTE** [comment]
Moot point, see other issue :-)
Cheers.
