### ISSUE TITLE
Error uploading

### ISSUE THREAD

**Issue by kd8skz** [M0LTE/adifpush#3]
when attempting to upload the I get the following message:
Cloudlog instance: http://192.168.1.70/Cloudlog
Watching /home/pi/.local/share/WSJT-X/wsjtx_log.adi, ctrl-c to quit...
Error uploading: File not found.
I've obviously screwed something up, but I have no idea where.

**Comment by M0LTE** [comment]
Hi @kd8skz I've substantially changed adifpush now so that it listens to WSJT-X's UDP output rather than watching the filesystem.

Feel free to give it another go. Thanks!
